#!/usr/bin/python3

import os
import MySQLdb

# assigning imported varibables
MY_HOST = os.environ.get('MY_HOST')
MY_USR = os.environ.get('MY_USR')
MY_PSWD = os.environ.get('MY_PSWD')

# connection to a database
db = MySQLdb.connect(host=MY_HOST, user=MY_USR, passwd=MY_PSWD, db='friends')

# getting a curse to navigate and manipulate query results
cur = db.cursor()

# cur.execute("CREATE TABLE songs(id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,title TEXT NOT NULL)")

songs = ('Perfect', 'The Joker And The Queen', 'Galway Gal')

# insert into the table
# for song in songs:
#     cur.execute("INSERT INTO songs (title) VALUES (%s)", (song,))
#     print ("Auto Increment ID: %s" % cur.lastrowid)


# numrows = cur.execute("SELECT * FROM songs")
# print ("Selected %s rows" % numrows)
# print ("Selected %s rows" % cur.rowcount)

# print results in comman delimited format
# cur.execute("SELECT * FROM songs")
# rows = cur.fetchall()

# for row in rows:
#     for col in row:
#         print(col)
#         print()


"""
FETCH ONE AT A TIME
"""
cur.execute("SELECT * FROM songs WHERE id = 9")
# result = cur.fetchone()

# # Check if result is not None before printing
# if result:
#     print("Id: %s -- Title: %s" % result)
# else:
#     print("No results found.")


""" RAISE EXCEPTIONS"""
try:
    cur.execute("SELECT * FROM songs")
    rows = cur.fetchall()
except MySQLdb.Error as e:
    try:
        print("MySQL Error [%d]: %s" % (e.args[0], e.args[1]))
    except IndexError:
        print("MySQL Error: %s" % str(e))

# Print results in comma delimited format
for row in rows:
    for col in row:
        print("%s," % col)
    print()



